version: '2'

services:
  web:
    build: .
    ports:
      - "5006:5006"
    env_file:
      - .env.production
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

# Para usar um banco de dados separado (opcional):
# volumes:
#   mysql_data:
#     driver: local

# services:
#   sise-db:
#     image: mariadb:10.6
#     container_name: sise-mariadb
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password_here
#       MYSQL_DATABASE: sise_db
#       MYSQL_USER: sise_user
#       MYSQL_PASSWORD: sise_password
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - sise-network
#     ports:
#       - "3306:3306"